<?php
require_once __DIR__ . '/../includes/formatos_guard.php';
require_once __DIR__ . '/../includes/formatos_ui.php';
require_once __DIR__ . '/../src/models/FormatoModel.php';
requireFormatosAccess();
$generados = FormatoModel::listarTerminacionesGeneradas(__DIR__ . '/../uploads/generados');
$csrf = csrfToken();
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AF-FT-02 · Terminación de contrato</title><link rel="stylesheet" href="./assets/css/tailwind.css"></head>
<body class="bg-gray-50 min-h-screen text-gray-800"><?php require __DIR__ . '/../includes/sidebar.php'; ?><div class="md:ml-64 pt-14 md:pt-0">
<?= formatosHeader('Terminación de contrato','AF-FT-02 · Notificación de terminación') ?>
<main class="p-3 sm:p-5 lg:p-6 max-w-5xl mx-auto space-y-5">
<section class="bg-white rounded-2xl border border-gray-100 shadow-sm"><div class="p-5 border-b border-gray-100"><h2 class="font-bold">Generar notificación</h2><p class="text-xs text-gray-600">Busca al empleado, registra sus renovaciones y selecciona la fecha final del contrato.</p></div>
<form id="formTerminacion" class="p-5 space-y-5"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf) ?>"><input type="hidden" name="cedula" id="termCedula">
<div><label class="block text-sm font-medium mb-1">Buscar empleado</label><input id="termBuscar" autocomplete="off" class="w-full h-10 border border-gray-200 rounded-lg px-3 text-sm" placeholder="Nombre o cédula"><div id="termResultados" class="mt-2 space-y-1"></div></div>
<div id="termEmpleado" class="hidden rounded-xl bg-gray-50 p-4 text-sm"></div>
<div id="termOpciones" class="hidden space-y-4">
<div><label class="block text-sm font-medium mb-1">Número de renovaciones</label><select id="termCantidad" class="w-full h-10 border border-gray-200 rounded-lg px-3"><option value="0">Sin renovaciones</option><?php for($i=1;$i<=20;$i++): ?><option value="<?= $i ?>"><?= $i ?> renovación<?= $i>1?'es':'' ?></option><?php endfor; ?></select><p class="text-xs text-gray-500 mt-1">Desde la cuarta renovación, la duración mínima es de 12 meses.</p></div>
<div id="termRenovaciones" class="space-y-3"></div>
<div><label class="block text-sm font-medium mb-1">Fecha fin del contrato que se notificará</label><select id="termFechaFin" name="fecha_fin" required class="w-full h-10 border border-gray-200 rounded-lg px-3"></select></div>
</div><div id="termError" class="hidden rounded-lg bg-red-50 border border-red-200 text-red-700 p-3 text-sm"></div>
<?= formatosBarraAcciones('btnGenerarTerm','terminacionReset()','submit') ?></form></section>
<section class="bg-white rounded-2xl border border-gray-100 shadow-sm"><div class="p-5 border-b border-gray-100"><h2 class="font-bold">Generados</h2><p class="text-xs text-gray-500">Notificaciones de terminación creadas</p></div><div class="p-5 space-y-2">
<?php if($generados): foreach($generados as $g): ?><div class="border border-gray-100 rounded-xl p-3 flex flex-wrap gap-3 items-center justify-between"><div class="min-w-0 flex-1"><p class="text-sm break-words"><?= htmlspecialchars($g['archivo']) ?></p><p class="text-xs text-gray-500"><?= date('d/m/Y H:i',$g['fecha']) ?></p></div><div class="flex gap-2"><a class="px-3 py-2 border rounded-lg text-sm" target="_blank" href="./api/formato_archivo.php?f=<?= rawurlencode($g['archivo']) ?>&accion=ver">Ver</a><a class="px-3 py-2 border rounded-lg text-sm" href="./api/formato_archivo.php?f=<?= rawurlencode($g['archivo']) ?>&accion=descargar">Descargar</a><button type="button" class="px-3 py-2 border border-red-200 text-red-600 rounded-lg text-sm" onclick="eliminarTerm(<?= htmlspecialchars(json_encode($g['archivo'],JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE)) ?>)">Eliminar</button></div></div><?php endforeach; else: ?><p class="text-center text-sm text-gray-500 py-5">Todavía no hay formatos generados.</p><?php endif; ?>
</div></section></main></div>
<script>
const csrfToken=<?= json_encode($csrf) ?>;let empleado=null, ren=[];
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function dt(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d);}
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function addMonths(start,n){let d=dt(start),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+Number(n));let last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));d.setDate(d.getDate()-1);return iso(d);}
function plusDay(s){let d=dt(s);d.setDate(d.getDate()+1);return iso(d);}
function fmt(s){if(!s)return '';let [y,m,d]=s.split('-');return `${d}/${m}/${y}`;}
function error(s){$('termError').textContent=s||'';$('termError').classList.toggle('hidden',!s);}
$('termBuscar').addEventListener('input',async()=>{const q=$('termBuscar').value.trim();if(q.length<2){$('termResultados').innerHTML='';return;}try{let r=await fetch('./api/formatos_renovacion_empleados.php?q='+encodeURIComponent(q));let j=await r.json();$('termResultados').innerHTML=(j.empleados||[]).map(e=>`<button type="button" class="block w-full text-left border rounded-lg p-3 hover:bg-gray-50 text-sm" data-emp="${esc(JSON.stringify(e))}"><b>${esc(e.nombre)}</b> · CC ${esc(e.cedula)}<div class="text-xs text-gray-500">${esc(e.cargo||'')} · Fin registrado: ${fmt(e.fecha_fin_contrato)}</div></button>`).join('')||'<p class="text-sm text-gray-500">No se encontraron empleados.</p>';document.querySelectorAll('[data-emp]').forEach(b=>b.onclick=()=>seleccionar(JSON.parse(b.dataset.emp)));}catch(e){error('No se pudo consultar la lista de empleados.');}});
function seleccionar(e){empleado=e;$('termCedula').value=e.cedula;$('termBuscar').value=e.nombre;$('termResultados').innerHTML='';$('termEmpleado').classList.remove('hidden');$('termEmpleado').innerHTML=`<b>${esc(e.nombre.toUpperCase())}</b><br>CC ${esc(e.cedula)} · ${esc(e.cargo||'Sin cargo')}<br>Inicio: ${fmt(e.fecha_inicio_contrato)} · Fin registrado: ${fmt(e.fecha_fin_contrato)}`;$('termOpciones').classList.remove('hidden');$('termCantidad').value='0';ren=[];renderRen();actualizarFechas();error('');}
$('termCantidad').addEventListener('change',()=>{let n=Number($('termCantidad').value);while(ren.length<n)ren.push({meses:ren.length>=3?12:6});ren=ren.slice(0,n);renderRen();actualizarFechas();});
function renderRen(){ $('termRenovaciones').innerHTML=ren.map((r,i)=>`<div class="border rounded-xl p-3"><div class="font-semibold text-sm mb-2">Renovación RN${i+1}</div><label class="block text-xs text-gray-500 mb-1">Duración</label><select data-ren="${i}" class="w-full h-10 border rounded-lg px-3">${[1,2,3,6,12,18,24,36].filter(m=>i<3||m>=12).map(m=>`<option value="${m}" ${m===r.meses?'selected':''}>${m<12?m+' meses':m===12?'12 meses (1 año)':m/12+' años'}</option>`).join('')}</select></div>`).join('');document.querySelectorAll('[data-ren]').forEach(s=>s.onchange=()=>{ren[Number(s.dataset.ren)].meses=Number(s.value);actualizarFechas();});}
function calcular(){let out=[{fecha:empleado.fecha_fin_contrato,label:'Contrato inicial · '+fmt(empleado.fecha_fin_contrato),n:0}],inicio=plusDay(empleado.fecha_fin_contrato);ren.forEach((r,i)=>{let fin=addMonths(inicio,r.meses);out.push({fecha:fin,label:`Después de RN${i+1} · ${fmt(fin)}`,n:i+1});inicio=plusDay(fin);});return out;}
function actualizarFechas(){if(!empleado)return;let opts=calcular();$('termFechaFin').innerHTML=opts.map(o=>`<option value="${o.fecha}" data-n="${o.n}">${o.label}</option>`).join('');}
function terminacionReset(){$('formTerminacion').reset();$('termCedula').value='';$('termEmpleado').classList.add('hidden');$('termOpciones').classList.add('hidden');$('termResultados').innerHTML='';empleado=null;ren=[];error('');}
$('formTerminacion').addEventListener('submit',async ev=>{ev.preventDefault();error('');if(!empleado)return error('Selecciona un empleado.');let fecha=$('termFechaFin').value;let index=calcular().findIndex(o=>o.fecha===fecha);let renovaciones=ren.slice(0,index).map(r=>r.meses);if(index<0)return error('Selecciona una fecha final válida.');for(let i=3;i<renovaciones.length;i++)if(renovaciones[i]<12)return error(`La renovación RN${i+1} debe ser de mínimo 12 meses.`);let fd=new FormData();fd.append('csrf_token',csrfToken);fd.append('cedula',empleado.cedula);fd.append('fecha_fin',fecha);fd.append('duraciones',JSON.stringify(renovaciones));let btn=$('btnGenerarTerm');btn.disabled=true;try{let r=await fetch('./api/formatos_terminacion_generar.php',{method:'POST',body:fd});let j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'No se pudo generar el Word.');location.reload();}catch(e){error(e.message);}finally{btn.disabled=false;}});
async function eliminarTerm(archivo){if(!confirm('¿Eliminar este formato?'))return;let fd=new FormData();fd.append('csrf_token',csrfToken);let r=await fetch('./api/formato_archivo.php?f='+encodeURIComponent(archivo)+'&accion=eliminar',{method:'POST',body:fd});let j=await r.json();if(j.ok)location.reload();else alert('No se pudo eliminar el archivo.');}
</script></body></html>